# Generated by Django 2.0.2 on 2018-04-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='AT',
            field=models.FloatField(max_length=6, verbose_name='Adequacao Tematica do Evento'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Quantidade_Tecnica',
            field=models.FloatField(max_length=6, verbose_name='Qualidade Tecnica'),
        ),
    ]
