# Generated by Django 2.0.2 on 2018-04-16 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0002_auto_20180409_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'verbose_name_plural': 'Artigos'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliacoes'},
        ),
        migrations.AlterModelOptions(
            name='avaliador',
            options={'verbose_name_plural': 'Avaliadores'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='AT',
            field=models.FloatField(max_length=2, verbose_name='Adequacao Tematica do Evento'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Inovacao',
            field=models.FloatField(max_length=2, verbose_name='Inovacao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Media',
            field=models.FloatField(max_length=2, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Metodoliga',
            field=models.FloatField(max_length=2),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Quantidade_Tecnica',
            field=models.FloatField(max_length=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Qualidade Tecnica'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='Resultado',
            field=models.FloatField(max_length=2),
        ),
    ]
